nodeLinker: node-modules
npmRegistryServer: https://dev-artifactory.corp.linkedin.com:8083/artifactory/api/npm/npm-external-new/
npmAlwaysAuth: false
npmScopes:
  linkedin:
    npmRegistryServer: https://dev-artifactory.corp.linkedin.com:8083/artifactory/api/npm/npm-internal/
  types:
    npmRegistryServer: https://dev-artifactory.corp.linkedin.com:8083/artifactory/api/npm/npm-external-new/

# https is required by default
unsafeHttpWhitelist:
  - '*.corp.linkedin.com'
caFilePath: /etc/lipki/public-ca.crt
